### ISSUE TITLE
Add robot boilerplate

### ISSUE THREAD

**Issue by AndrewLester** [frc1418/2021-robot#1]
Add the boilerplate code for the robot. This includes the classes in the main package, and subfolders for our subsystems and commands. It may be a good idea to consider Tim's suggestion [here](https://github.com/frc1418/2020-offseason/issues/17) when creating the package structure.

**Comment by ArchdukeTim** [comment]
Before you add anything, I want to show you an example of how you should set up your subsystems so that you can write tests for them.
